version: '3.8'
services:
    app:
        image: webSister
        container_name: web-server
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./php/nama-projek:/var/www/html/Coba
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE: TugasBesarWeb1
            MYSQL_USER: root
            MYSQL_PASSWORD: 
        ports:
            - "9906:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '3060:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
